#Should the plugin check for updates?
UpdateChecker: true

#Should claiming rewards be disabled in any worlds? (playtime is still counted)
DisableGettingRewardsInWorlds:
    #- world
    #- world_nether
    #- world_the_end
    
#(*) are required fields for a reward.
Rewards:
    #Reward names should be unique.
    TestReward:
        #(*)
        #This name will be shown to players
        DisplayName: "Test Reward"
        
        #(*)
        #How many minutes should a player have to play on the server to be eligible for this reward?
        #In minutes, minimum is 1.
        #It is possible to give multiple times: 60,80,100. This will give the same reward after 60 minutes, then after 80, then after 100 and never again afterwards (if not looping).
        PlaytimeNeeded: 60
        
        #Should afk playtime be counted towards this reward?
        #THIS REQUIRES ESSENTIALSX TO BE INSTALLED ON YOUR SERVER!
        #Default = true
        CountAfkTime: false
        
        #How many open inventory spaces would the player need to claim this reward?
        #Default = 0
        SlotsNeeded: 1
        
        #Should the player be able te receive this reward every time he/she reaches the PlaytimeNeeded or just once?
        #False will only give it once.
        #Default = false
        Loop: true
        
        #Should the playtime in certain worlds not be counted towards the playtime for this reward?
        #Default = no disabled worlds
        DisabledWorlds:
            - world_nether
            - world_the_end
        
        #How should the notification and broadcast be displayed?
        #bossbar/actionbar/chat
        #Default = chat
        NotificationType: bossbar
        
        #(*)
        #What message should be send to the player upon receiving this reward?
        #Color codes may be used https://wiki.ess3.net/mc/ as well as \n for a new line.
        #Leave blank to disable.
        #Placholders: %player%
        Notification: "You have received the Test Reward! Congratulations!"
        
        #(*)
        #What message should be broadcasted upon player receiving this reward?
        #Color codes may be used https://wiki.ess3.net/mc/ as well as \n for a new line.
        #Leave blank to disable.
        #Placholders: %player%
        BroadcastNotification: "%player% has been awarded with the test reward!"
        
        #(*)
        #What commands should be executed upon receiving this reward?
        #Placholders: %player%
        Commands:
            - "give %player% dirt 1"
    TestReward2:
        DisplayName: "Test Reward 2"
        PlaytimeNeeded: 20,40,100,120,50
        SlotsNeeded: 2
        Notification: "You have received the Test Reward 2! Congratulations!"
        BroadcastNotification: ""
        Commands:
            - "give %player% dirt 1"
            - "give %player% grass_block 1"