#Should the plugin check for updates?
UpdateChecker: true

#Allow the plugin to collect anonymous data from your server for a better understanding who and how people are using this plugin.
#There is really no reason to opt-out, but here it is!
bStats: true

#After how much playtime should the player data be autosaved?
#In minutes, minimum is 1.
AutoSave: 1

#How long should the plugin save the playerdata in cache after logout?
#This will save performance for RAM.
#In minutes, minimum is 0.
TimeKeepDataInCache: 5

#Should the plugin also count playtime from before it was installed?
#It will not give rewards for this playtime.
CountAllPlaytime: true

#Should claiming rewards be disabled in any worlds?
#Rewards that require claiming will be put into pending state until in allowed world.
DisableGettingRewardsInWorlds:
    #- world
    #- world_nether
    #- world_the_end
    
#(*) are required fields for a reward.
Rewards:
    #Reward names should be unique.
    TestReward:
        #This name will be displayed for the reward in the rewards GUI.
        #This name does not need be unique.
        #Color codes may be used https://wiki.ess3.net/mc/.
        #Default = reward name
        DisplayName: "&6Test &eReward"
        
        #This item will be displayed for the reward in the rewards GUI.
        #All possible materials (except for AIR) can be used for this (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html ).
        #Default = chest
        DisplayItem: "ender_chest"
        
        #The item in the reward GUI will have this description.
        #Color codes may be used https://wiki.ess3.net/mc/.
        #Each list item will be a new line.
        #Default = empty (no description)
        DisplayDescription:
            - "This will go on the first line."
            - "This will go on the second line."
            - "This will go on the third line."
        
        #(*)
        #How long should a player have to play on the server to be eligible for this reward?
        #In minutes, minimum is 1.
        #It is possible to give multiple times: 60,80,100. This will give the reward after 60 minutes, then after 80, then after 100 and never again afterwards (if not looping).
        PlaytimeNeeded: 60
        
        #Should afk playtime be counted towards this reward?
        #REQUIRES ESSENTIALSX TO BE INSTALLED ON YOUR SERVER!
        #Default = true
        CountAfkTime: false
        
        #How many open inventory spaces would the player need to claim this reward?
        #Default = 0
        SlotsNeeded: 2
        
        #Should the player be able te receive this reward every time he/she reaches the PlaytimeNeeded or just once?
        #False will only give it once.
        #Default = false
        Loop: true
        
        #Should the playtime in certain worlds not be counted towards the playtime for this reward?
        #Default = no disabled worlds
        DisabledWorlds:
            - "world_nether"
            - "world_the_end"
            
        #Should this reward only be given to players with the permission 'liteplaytimerewards.reward.<rewardname>' (permission has to be all lower case)?
        #Setting this to false will give the reward to everyone.
        #Default = false
        UsePermission: true
        
        #How should the notification and broadcast be displayed?
        #bossbar/actionbar/chat
        #Default = chat
        NotificationType: "bossbar"
        
        #What message should be send to the player upon receiving this reward?
        #Color codes may be used https://wiki.ess3.net/mc/ as well as \n for a new line.
        #Default = no notification
        #Placholders: %player%
        Notification: "You have received the Test Reward! Congratulations!"
        
        #What message should be broadcasted upon player receiving this reward?
        #Color codes may be used https://wiki.ess3.net/mc/ as well as \n for a new line.
        #Default = no broadcast notification
        #Placholders: %player%
        BroadcastNotification: "%player% has been awarded with the test reward!"
        
        #(*)
        #What commands should be executed upon receiving this reward?
        #Placholders: %player%
        Commands:
            - "give %player% dirt 1"
            - "give %player% grass_block 1"
    TestReward2:
        PlaytimeNeeded: 20,40,100,120,50
        Notification: "You have received the Test Reward 2! Congratulations!"
        Commands:
            - "effect give %player% haste 1 1"