#Should the plugin check for updates?
UpdateChecker: true

#Should the plugin automatically check if players are eligible for any reward on player join?
CheckAvailableRewardsOnPlayerJoin: true

#How many minutes should be between each reward check? The lower this value the more accurate people will get their reward at cost of performance.
#I would recommend not setting this lower than 30 to avoid lag, especially with many active players.
#In minutes, minimum is 1.
RewardCheck: 60

#Should getting rewards be disabled in any worlds?
DisableGettingRewardsInWorlds:
    #- world
    #- world_nether
    #- world_the_end
    
Rewards:
    TestReward:
        #This name will be shown to players
        DisplayName: "Test Reward"
        #How many minutes should a player have to play on the server to be eligible for this reward?
        #In minutes, minimum is 1.
        PlaytimeNeeded: 60
        #Should players receive the rewards from the playtime before this plugin was installed or start counting playtime from now on?
        #True will also count playtime from before this plugin was installed, false does not.
        CountPlaytimeFromStart: false
        #Should the player be able te receive this reward every time he/she reaches the PlaytimeNeeded or just once?
        #False will only give it once.
        Loop: true
        #What message should be send to the player upon receiving this reward?
        #Color codes may be used https://wiki.ess3.net/mc/ as well as \n for a new line.
        #Leave blank to disable.
        #Placholders: %player%
        Notification: "You have received the Test Reward! Congratulations!"
        #What message should be broadcasted upon player receiving this reward?
        #Color codes may be used https://wiki.ess3.net/mc/ as well as \n for a new line.
        #Leave blank to disable.
        #Placholders: %player%
        BroadcastNotification: "%player% has been awarded with the test reward!"
        #What commands should be executed upon receiving this reward?
        #Placholders: %player%
        Commands:
            - "give %player% dirt 1"